### ISSUE TITLE
Not generating api specs

### ISSUE THREAD

**Issue by karthik2872** [james-hu/apig-swagger-ui#1]
When run with us-east-2 region in the command line from my mac terminal - 

npx apig-swagger-ui -r us-east-2 -s

I see a browser tab showing - Could not render n , see the console 

No API definition provided

IS there a way to set the aws profile on your cli to ensure your utility is using the correct profile ?

**Comment by james-hu** [comment]
Hi @karthik2872 , I think that's because there's nothing in API Gateway in us-east-2 region. If you check your Mac Terminal, I think you would see just these two lines:
```
Generating files to: api-doc
Local server started. Ctrl-C to stop. Access URL: http://localhost:8001/
```

If there are APIs in API Gateway, you should be able to see something like this:
```
Generating files to: api-doc
Generating OpenAPI spec for: ...<your actual API URL>...
Generating OpenAPI spec for: ...<your actual API URL>...
Generating OpenAPI spec for: ...<your actual API URL>...
...
Local server started. Ctrl-C to stop. Access URL: http://localhost:8001/
```

**Comment by karthik2872** [comment]
I would like to use a aws profile different from the default profile . I have api end points in the custom profile ( different from the default ) , does your CLI have a parameter to set the profile explicitly ? Or does your cli look at api gateway and end points in the default profile only ?

**Comment by james-hu** [comment]
apig-swagger-ui can pick up the AWS profile you specify. For how to specify AWS profile, you can try `export AWS_PROFILE=<your profile>`. Here's the documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by james-hu** [comment]
Closing as there's no further feedback.
